# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-06 00:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arrival',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Arrival_ID', models.CharField(max_length=10)),
                ('Arrival_Date_Time', models.DateTimeField(verbose_name='date arrival')),
                ('Flight_Feedback', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dest_ID', models.CharField(max_length=10)),
                ('Destination_Name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Post_ID', models.CharField(max_length=10)),
                ('Post_Date_Time', models.DateTimeField(verbose_name='date post')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Type_ID', models.CharField(max_length=10)),
                ('Prodcut_Type_Name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_ID', models.CharField(max_length=10)),
                ('Prodcut_Name', models.CharField(max_length=200)),
                ('Prodcut_Type', models.CharField(max_length=20)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Responds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Response_Date_Time', models.DateTimeField(verbose_name='date responded')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SaudiStudentOrganization.Post')),
            ],
        ),
        migrations.CreateModel(
            name='Saudi_Group_Admins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Admin_ID', models.CharField(max_length=10)),
                ('Frist_Name', models.CharField(max_length=200)),
                ('Last_Name', models.CharField(max_length=200)),
                ('Email', models.CharField(max_length=200)),
                ('Phone_Number', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Frist_Name', models.CharField(max_length=200)),
                ('Last_Name', models.CharField(max_length=200)),
                ('Email', models.CharField(max_length=200)),
                ('Phone_Number', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Student_Arrival',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SaudiStudentOrganization.Arrival')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SaudiStudentOrganization.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Student_Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SaudiStudentOrganization.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Tour_Destinations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SaudiStudentOrganization.Destination')),
            ],
        ),
        migrations.CreateModel(
            name='Tours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tour_ID', models.CharField(max_length=10)),
                ('Tour_Date_Time', models.DateTimeField(verbose_name='date tour')),
            ],
        ),
        migrations.AddField(
            model_name='tour_destinations',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SaudiStudentOrganization.Tours'),
        ),
        migrations.AddField(
            model_name='student_tour',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SaudiStudentOrganization.Tours'),
        ),
        migrations.AddField(
            model_name='responds',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SaudiStudentOrganization.Student'),
        ),
    ]
